version: '3.8'

services:
  ros_drl:
    restart: unless-stopped
    container_name: ros_drl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11311:11311"
      - "6006:6006"
    volumes:
      - ../DRL-robot-navigation/:/catkin_ws/src/DRL-robot-navigation/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_PORT_SIM=11311
      - GAZEBO_RESOURCE_PATH=/catkin_ws/src/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
