version: '3.8'

services:
  ros2_drl:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ros2_drl
    ports:
      - "6006:6006"
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./deep_rl_robot_navigation:/ros2_ws/src/deep_rl_robot_navigation:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility
                - compute
                - video
